remote_theme: pages-themes/hacker@v0.2.0
title: Stoffer's GitHome
description: [GitHome Little Dogies](https://www.youtube.com/watch?v=Q2cFji4CmHE)


output:
  md_document:
    variant: markdown_github
    preserve_yaml: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Default YAML values (more information on Jekyll's site)
defaults:
  -
      ext-js: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"
